name: Linting Angular

on:
  push:
    branches: [main]

jobs:
  Linter-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: npm install
      - run: npm run lint
